# From the USD repository root folder, runm
# docker build build_scripts
FROM centos:7

RUN yum install -y \
        # USD
        glew-devel.x86_64 \
        libXcursor-devel.x86_64 \
        libXrandr-devel.x86_64 \
        libXinerama-devel.x86_64 \
        libXi-devel.x86_64 \
        # PySide https://pyside.readthedocs.io/en/latest/building/linux.html
        gcc-c++ \
        # clang \  # Not working for CentOS
        cmake \
        make \
        git \
        phonon-devel \
        libslt-devel \
        libxml2-devel \
        python-devel \
        # libslt-python \  # Not sure if needed
        qt-devel \
    & curl -s https://bootstrap.pypa.io/get-pip.py | python - \
    & wait

