# From the USD repository root folder, runm
# docker build build_scripts
ARG YUM_IMAGE
FROM $YUM_IMAGE

ARG INSTALL_DIR=/usd

# Building PySide can take a bloody long time
RUN pip install --target ${INSTALL_DIR}/lib/python PyOpenGL PySide
ENV PATH=${PATH}:${INSTALL_DIR}/lib/python/bin
ENV PYTHONPATH=${INSTALL_DIR}/lib/python
